services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: unless-stopped
    ports:
      - 6157:6157 # HTTP port
    volumes:
      - $HOME/.opengist:/opengist
    environment:
      OG_LOG_LEVEL: error

networks:
  homelab:
    driver: bridge